[env:esp32cam_cam1]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
build_flags =
	-DAPP_I2C_ADDR=0x24
	-DAPP_DEFAULT_CAMERA_ID=1
lib_deps =
	espressif/esp32-camera@^2.0.4
	links2004/WebSockets@^2.6.1
	bblanchon/ArduinoJson@^7.1.0

; [env:esp32cam_cam2]
; platform = espressif32
; board = esp32cam
; framework = arduino
; monitor_speed = 115200
; monitor_dtr = 0
; monitor_rts = 0
; monitor_filters = esp32_exception_decoder, time
; build_flags =
; 	-DAPP_I2C_ADDR=0x25
; 	-DAPP_DEFAULT_CAMERA_ID=2
; lib_deps =
; 	espressif/esp32-camera@^2.0.4
; 	links2004/WebSockets@^2.6.1
; 	bblanchon/ArduinoJson@^7.1.0
